# Generated by Django 5.1.7 on 2025-05-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_deleted_message_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
    ]
